config/routes.rb
DoctorPrototype::Application.routes.draw do

  root :to => 'years#index'

  put 'years/:year_id/clashes',
    :to => 'clashes#update',
    :as => :update_clashes

  delete 'years/:year_id/unclashables',
    :to => 'unclashables#remove',
    :as => :remove_unclashable

  put 'years/:id/generate_timetable',
    :to => 'years#generate_timetable',
    :as => :year_generate_timetable

  resources :years, :except => [:destroy] do
    resources :requirements, :only => [] do
      collection do
        post 'import'
      end
    end
    resources :precisely_clauses, :only => [:index] do
      collection do
        put 'update'
      end
    end
    resources :preference_clauses, :only => [:index] do
      collection do
        put 'update'
      end
    end
    resources :terms, :only => [] do
      member do
        get 'timetable_slots'
      end
    end
    resources :lecturers, :only => [] do
      collection do
        post 'import'
      end
    end
    resources :rooms, :except => [:show] do
      member do
        get 'timetable_slots'
      end
    end
    resources :degree_classes, :only => [:index, :show] do
      collection do
        post 'import'
      end
    end
    resources :staff_members, :only => [:index, :show] do
      collection do
        post 'import'
      end
    end
    resources :lecture_courses, :only => [:index, :show], :constraints => { :id => /[^\/]+(?=\.html\z|\.json\z)|[^\/]+/ } do
      member do
        post 'show_clashes'
        delete 'hide_clashes'
        put 'update_course_weeks'
      end
      collection do
        post 'import'
      end
    end
    resources :clashes, :only => [:index, :new]
    resources :unclashables, :only => [:create]
    resources :timetable_slots, :only => [:index]
  end
end

app/models/timetable_slot.rb
class TimetableSlot < ActiveRecord::Base

  attr_accessible :lecture_course, :room, :time_slot, :week, :slot_type

  # = Validations =
  validates_presence_of :lecture_course, :room, :time_slot, :week, :slot_type

  # = Relationships =
  belongs_to :lecture_course
  belongs_to :room
  belongs_to :time_slot
  belongs_to :week

end

app/controllers/timetable_slots_controller.rb
class TimetableSlotsController < ApplicationController
  def index
    @year = Year.find_by_no(params[:year_id])
    @rooms = @year.rooms
    @terms = @year.terms
  end
end

app/helpers/timetable_slots_helper.rb
module TimetableSlotsHelper
  def get_week_ranges(weeks)
    weeks.to_enum(:chunk).with_index { |x, idx| x - idx }.map do |diff, group|
      [group.first, group.last]
    end.map { |x| "#{x.first}-#{x.last}" }.join(", ")
  end
end

app/views/timetable_slots/index.html.erb
<div class="row" id='inner-header'>
  <div class='span6 sub-header'>
    <h2>
      View Timetable
    </h2>
  </div>
  <div class='span6 sub-header'>
    <div class='header-actions'>
      <%= back_button(@year.no, year_path(@year)) %>
    </div>
  </div>
</div>

<hr>

<h4>
  By Term
</h4>

<ul class='nav nav-pills nav-stacked'>
  <% @terms.each do |t| %>
    <li>
      <%= link_to "Term #{t.no}", timetable_slots_year_term_path(@year, t) %>
    </li>
  <% end %>
</ul>

<hr>

<h4>
  By Room
</h4>

<ul class='nav nav-pills nav-stacked'>
  <% @rooms.each do |r| %>
    <li>
      <%= link_to "Room #{r.no}", timetable_slots_year_room_path(@year, r) %>
    </li>
  <% end %>
</ul>