config/routes.rb
DoctorPrototype::Application.routes.draw do

  root :to => 'years#index'

  put 'years/:year_id/clashes',
    :to => 'clashes#update',
    :as => :update_clashes

  delete 'years/:year_id/unclashables',
    :to => 'unclashables#remove',
    :as => :remove_unclashable

  put 'years/:id/generate_timetable',
    :to => 'years#generate_timetable',
    :as => :year_generate_timetable

  resources :years, :except => [:destroy] do
    resources :requirements, :only => [] do
      collection do
        post 'import'
      end
    end
    resources :precisely_clauses, :only => [:index] do
      collection do
        put 'update'
      end
    end
    resources :preference_clauses, :only => [:index] do
      collection do
        put 'update'
      end
    end
    resources :terms, :only => [] do
      member do
        get 'timetable_slots'
      end
    end
    resources :lecturers, :only => [] do
      collection do
        post 'import'
      end
    end
    resources :rooms, :except => [:show] do
      member do
        get 'timetable_slots'
      end
    end
    resources :degree_classes, :only => [:index, :show] do
      collection do
        post 'import'
      end
    end
    resources :staff_members, :only => [:index, :show] do
      collection do
        post 'import'
      end
    end
    resources :lecture_courses, :only => [:index, :show], :constraints => { :id => /[^\/]+(?=\.html\z|\.json\z)|[^\/]+/ } do
      member do
        post 'show_clashes'
        delete 'hide_clashes'
        put 'update_course_weeks'
      end
      collection do
        post 'import'
      end
    end
    resources :clashes, :only => [:index, :new]
    resources :unclashables, :only => [:create]
    resources :timetable_slots, :only => [:index]
  end
end

app/controllers/lecture_courses_controller.rb
class LectureCoursesController < ApplicationController
  def index
    @year = Year.find_by_no(params[:year_id])
    @courses = @year.lecture_courses.by_code
  end

  def show
    @year = Year.find_by_no(params[:year_id])
    @course = @year.lecture_courses.find_by_code(params[:id])
    @requirements = @course.requirements
    @lecturers = @course.lecturers

    courses = @year.lecture_courses.by_code
    course_index = courses.index(@course)
    @prev_5 = courses.take(course_index).last(5)
    @next_5 = courses.drop(course_index + 1).take(5)
  end

  def show_clashes
    @year = Year.find_by_no(params[:year_id])
    @course = @year.lecture_courses.find_by_code(params[:id])
    @course.update_attribute(:clashes_hidden, false)

    render :nothing => true
  end

  def hide_clashes
    @year = Year.find_by_no(params[:year_id])
    @course = @year.lecture_courses.find_by_code(params[:id])
    @course.update_attribute(:clashes_hidden, true)

    render :nothing => true
  end

  def import
    @year = Year.find_by_no(params[:year_id])
    tempfile = params[:file]
    FileUtils::cp(tempfile.tempfile.path, Rails.root.join("tmp", tempfile.original_filename))
    Resque.enqueue(LectureCourseImporterWorker, @year.no, tempfile.original_filename)
    redirect_to year_path(@year), :notice => "Importing lecture courses."
  end

  def update_course_weeks
    @year = Year.find_by_no(params[:year_id])
    @course = @year.lecture_courses.find_by_code(params[:id])
    @course.course_weeks.for_year(@year).destroy_all

    allocations = params[:course_weeks]

    if allocations
      # Update the course to reflect whether the lecturers are merged or not
      merged_lecturers = allocations.delete("merged_lecturers")
      scheduling_type = allocations.delete("scheduling_type")
      size = allocations.delete("size")
      @course.merged_lecturers = merged_lecturers.present?
      @course.scheduling_type = scheduling_type
      @course.size = size
      @course.save!
      @course.reload

      lecture_allocations = allocations.delete("lectures")
      if lecture_allocations
        # If they are merged, only add rows with no staff_member_id
        if @course.merged_lecturers
          lecture_allocations.select! { |k, _| k == "all" }
          lecture_allocations.each do |_, term_allocations|
            term_allocations.each do |term_no, week_allocations|
              term = @year.terms.find_by_no(term_no)
              if @course.taught_in_term?(term)
                week_allocations.each do |week_no, no_hours|
                  week = term.weeks.find_by_no(week_no)
                  if week
                    hours = no_hours.to_i
                    CourseWeek.create!(:lecture_course => @course, :week => week, :staff_member => nil, :hours => hours, :session_type => "Lecture")
                  end
                end
              end
            end
          end
        # If they are not merged, add rows for each staff member
        else
          lecture_allocations.reject! { |k, _| k == "all" }
          lecture_allocations.each do |login, term_allocations|
            staff = @year.staff_members.find_by_login(login)
            term_allocations.each do |term_no, week_allocations|
              term = @year.terms.find_by_no(term_no)
              if @course.taught_in_term?(term)
                week_allocations.each do |week_no, no_hours|
                  week = term.weeks.find_by_no(week_no)
                  if week
                    hours = no_hours.to_i
                    CourseWeek.create!(:lecture_course => @course, :week => week, :staff_member => staff, :hours => hours, :session_type => "Lecture")
                  end
                end
              end
            end
          end
        end
      end

      tutorial_allocations = allocations.delete("tutorials")
      if tutorial_allocations
        tutorial_allocations.each do |term_no, week_allocations|
          term = @year.terms.find_by_no(term_no)
          if @course.taught_in_term?(term)
            week_allocations.each do |week_no, no_hours|
              week = term.weeks.find_by_no(week_no)
              if week
                hours = no_hours.to_i
                CourseWeek.create!(:lecture_course => @course, :week => week, :staff_member => nil, :hours => hours, :session_type => "Tutorial")
              end
            end
          end
        end
      end

      lab_allocations = allocations.delete("labs")
      if lab_allocations
        lab_allocations.each do |term_no, week_allocations|
          term = @year.terms.find_by_no(term_no)
          if @course.taught_in_term?(term)
            week_allocations.each do |week_no, no_hours|
              week = term.weeks.find_by_no(week_no)
              if week
                hours = no_hours.to_i
                CourseWeek.create!(:lecture_course => @course, :week => week, :staff_member => nil, :hours => hours, :session_type => "Lab")
              end
            end
          end
        end
      end
    else
      @course.merged_lecturers = false
      @course.save!
    end

    Resque.enqueue(CourseWeekWriterWorker, @year.no)
    redirect_to year_lecture_course_path(@year, @course), :notice => "Selections were updated successfully."
  end
end

app/helpers/lecture_courses_helper.rb
module LectureCoursesHelper
  def find_existing_hours(course_weeks, week, lecturer, type)
    existing = course_weeks.where(:week_id => week, :staff_member_id => lecturer, :session_type => type)
    if existing.present?
      existing.first.hours
    else
      0
    end
  end

  def investigation_class(course)
    course.total_hours == 27 ? "standard" : "investigation"
  end

  def scheduling_type_options(course)
    options = []
    types = [
      ['a', ''],
      ['b', ''],
      ['c', ''],
      ['b1', ' (LT-L)'],
      ['b2', ' (L-LT)'],
      ['b3', ' (L-TL)'],
      ['b4', ' (TL-L)'],
      ['c1', ' (LT-L)'],
      ['c2', ' (L-LT)'],
      ['c3', ' (L-TL)'],
      ['c4', ' (TL-L)']
    ]

    types.each do |type|
      options << ["Type #{type[0]}#{type[1]}", type[0]]
    end

    options_for_select(options, course.scheduling_type)
  end

  def course_size_options(course)
    options = []
    ['small', 'medium', 'large'].each do |size|
      options << [size.capitalize, size]
    end

    options_for_select(options, course.size)
  end
end

app/views/lecture_courses/_course_header.html.erb
<tr class='header'>
  <th rowspan="2" class="lecturer-header">
    Lecturer
  </th>

  <% @year.terms.each do |t| %>
    <% if @course.taught_in_term?(t) %>
      <th colspan="<%= t.weeks.count + 1 %>">
        <%= "Term #{t.no}" %>
      </th>
    <% end %>
  <% end %>
  <th></th>
</tr>

<tr class='header'>
  <% @year.terms.each do |t| %>
    <% if @course.taught_in_term?(t) %>
      <% t.weeks.each do |w| %>
        <th class="week-header">
          <%= w.no %>
        </th>
      <% end %>
      <th class="default-header"></th>
    <% end %>
  <% end %>
</tr>

app/views/lecture_courses/_course_merged.html.erb
<tr class="merged-row <%= @course.merged_lecturers ? '' : 'hidden' %>">
  <td>
    All lecturers
  </td>
  <% @year.terms.each do |t| %>
    <% if @course.taught_in_term?(t) %>
      <% t.weeks.each do |w| %>
        <td>
          <%= text_field_tag "course_weeks[lectures][all][#{t.no}][#{w.no}]", find_existing_hours(@course.course_weeks, w, nil, "Lecture"), :class => "tiny term-#{t.no} merged", :id => "#{t.no}-#{w.no}-all" %>
        </td>
      <% end %>
      <td>
        <div class="control-group">
          <div class="controls">
            <%= link_to "Select Defaults", "#", :class => "btn btn-mini defaults term-#{t.no}", :id => "#{t.no}-all-defaults" %>
          </div>
        </div>
      </td>
    <% end %>
  <% end %>
</tr>

app/views/lecture_courses/_course_single.html.erb
<% @course.lecturers.only_lecturers.each_with_index do |l, i| %>
  <tr class="single-row <%= @course.merged_lecturers ? 'hidden' : '' %>">
    <td>
      <%= "#{l.staff_member.full_name} (#{l.staff_member.login})" %>
    </td>
    <% @year.terms.each do |t| %>
      <% if @course.taught_in_term?(t) %>
        <% t.weeks.each do |w| %>
          <td>
            <%= text_field_tag "course_weeks[lectures][#{l.staff_member.login}][#{t.no}][#{w.no}]", find_existing_hours(@course.course_weeks, w, l.staff_member, "Lecture"), :class => "tiny term-#{t.no} single", :id => "#{t.no}-#{w.no}-#{l.staff_member.login}" %>
          </td>
        <% end %>
        <td>
          <div class="control-group">
            <div class="controls">
              <%= link_to "Select Defaults", "#", :class => "btn btn-mini defaults term-#{t.no}", :id => "#{t.no}-#{l.staff_member.login}-defaults" %>
            </div>
          </div>
        </td>
      <% end %>
    <% end %>
  </tr>
<% end %>

app/views/lecture_courses/_course_summary.html.erb
<table class='summary'>
  <tr>
    <th class='type'></th>
    <th class='hours'>
      Hours
    </th>
  </tr>

  <tr>
    <td>
      Lectures
    </td>
    <td class='lecture-count'>
      0
    </td>
  </tr>
  <tr>
    <td>
      Tutorials
    </td>
    <td class='tutorial-count'>
      0
    </td>
  </tr>
  <tr>
    <td>
      Labs
    </td>
    <td class='lab-count'>
      0
    </td>
  </tr>
  <tr>
    <td>
      Total
    </td>
    <td class='total'>
      0
    </td>
  </tr>
</table>

app/views/lecture_courses/_course_weeks.html.erb
<div class='course-weeks'>
  <div class='row-fluid'>
    <div class='span2'>
      <ul class='nav nav-pills nav-stacked'>
        <% @prev_5.each do |n| %>
          <li>
            <%= link_to n.code, year_lecture_course_path(@year, n) %>
          </li>
        <% end %>

        <strong>
          <li>
            <%= @course.code %>
          </li>
        </strong>

        <% @next_5.each do |n| %>
          <li>
            <%= link_to n.code, year_lecture_course_path(@year, n) %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class='span10'>
      <h4>
        Course-week Selection
      </h4>

      <%= form_tag update_course_weeks_year_lecture_course_path(@year, @course), :method => :put do %>
        <% if @course.has_multiple_lecturers? %>
          <label class="checkbox">
            <%= check_box_tag "course_weeks[merged_lecturers]", true, @course.merged_lecturers, :class => "merged-lecturers", :id => "merge" %>
            Schedule lecturers concurrently?
          </label>
        <% end %>

        <div class="scheduling-type">
          <label class="control-label">
            Scheduling type
          </label>
          <div class="controls">
            <%= select_tag "course_weeks[scheduling_type]", scheduling_type_options(@course), :include_blank => true, :class => "input-medium" %>
          </div>
        </div>

        <div class="scheduling-type">
          <label class="control-label">
            Size
          </label>
          <div class="controls">
            <%= select_tag "course_weeks[size]", course_size_options(@course), :include_blank => true, :class => "input-medium" %>
          </div>
        </div>

        <table>
          <%= render :partial => 'course_header' %>
          <%= render :partial => 'course_single' %>
          <% if @course.has_multiple_lecturers? %>
            <%= render :partial => 'course_merged' %>
          <% end %>
          <%= render :partial => 'tutorial_hours' %>
          <%= render :partial => 'lab_hours' %>
          <%= render :partial => 'course_summary' %>
        </table>

        <div class='form-actions'>
          <%= submit_tag "Submit", :class => 'btn btn-primary' %>
          <%= link_to "Cancel", year_path(@year), :class => 'btn btn-danger' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/lecture_courses/_import_form.html.erb
<%= form_tag(import_year_lecture_courses_path(@year), :multipart => true, :class => "form-horizontal") do %>
  <h3>
    Import Lecture Courses
  </h3>

  <div class='control-group'>
    <div class='controls'>
      <%= file_field_tag "file" %>
    </div>
  </div>

  <div class='form-actions'>
    <%= submit_tag "Upload", :class => 'btn btn-primary' %>
  </div>

<% end %>

app/views/lecture_courses/_lab_hours.html.erb
<tr class="lab-hours">
  <td>
    Lab hours
  </td>
  <% @year.terms.each do |t| %>
    <% if @course.taught_in_term?(t) %>
      <% t.weeks.each do |w| %>
        <td>
          <%= text_field_tag "course_weeks[labs][#{t.no}][#{w.no}]", find_existing_hours(@course.course_weeks, w, nil, "Lab"), :class => "tiny term-#{t.no} lab", :id => "#{t.no}-#{w.no}-lab" %>
        </td>
      <% end %>
      <td></td>
    <% end %>
  <% end %>
</tr>

app/views/lecture_courses/_tutorial_hours.html.erb
<tr class="tutorial-hours">
  <td>
    Tutorial hours
  </td>
  <% @year.terms.each do |t| %>
    <% if @course.taught_in_term?(t) %>
      <% t.weeks.each do |w| %>
        <td>
          <%= text_field_tag "course_weeks[tutorials][#{t.no}][#{w.no}]", find_existing_hours(@course.course_weeks, w, nil, "Tutorial"), :class => "tiny term-#{t.no} tutorial", :id => "#{t.no}-#{w.no}-tutorial" %>
        </td>
      <% end %>
      <td></td>
    <% end %>
  <% end %>
</tr>

app/views/lecture_courses/index.html.erb
<div class="row" id='inner-header'>
  <div class='span6 sub-header'>
    <h2>
      Lecture Courses
    </h2>
  </div>
  <div class='span6 sub-header'>
    <div class='header-actions'>
      <%= back_button(@year.no, year_path(@year)) %>
    </div>
  </div>
</div>

<hr>

<% if @courses.empty? %>
  <div class="alert alert-block">
    No courses to show.
  </div>
<% else %>
  <ul class='nav nav-pills nav-stacked'>
    <% @courses.each do |c| %>
      <li>
        <%= link_to "#{c.code} - #{c.title}", year_lecture_course_path(@year, c) %>
      </li>
    <% end %>
  </ul>
<% end %>

<hr>

<%= render :partial => 'import_form' %>

<hr>

<%= render :partial => 'requirements/import_form' %>

<hr>

<%= render :partial => 'lecturers/import_form' %>

app/views/lecture_courses/show.html.erb
<div class="row" id='inner-header'>
  <div class='span6 sub-header'>
    <h2>
      <%= @course.code %> - <%= @course.title %>
    </h2>
  </div>
  <div class='span6 sub-header'>
    <div class='header-actions'>
      <%= back_button("courses", year_lecture_courses_path(@year)) %>
    </div>
  </div>
</div>

<hr>

<%= render :partial => 'course_weeks' %>

<hr>

<div class="row">
  <div class="span6">
    <% if @requirements.empty? %>
      <h3>
        There are no requirements for this course.
      </h3>
    <% else %>
      <h3>
        Option for:
      </h3>
      <% @requirements.group_by(&:required).each do |required, classes| %>
        <h4>
          <%= required %>
        </h4>
        <ul class='nav nav-pills nav-stacked'>
          <% classes.each do |c| %>
            <li>
              <%= link_to "#{c.degree_class.degreeyr} - #{c.degree_class.title}", year_degree_class_path(@year, c.degree_class) %>
            </li>
          <% end %>
        </ul>
      <% end %>
    <% end %>
  </div>

  <div class="span6">
    <% if @lecturers.empty? %>
      <h3>
        There are no staff members for this course.
      </h3>
    <% else %>
      <h3>
        Taught by:
      </h3>
      <% @lecturers.group_by(&:role).each do |role, staff| %>
        <h4>
          <%= role %>
        </h4>
        <ul class='nav nav-pills nav-stacked'>
          <% staff.each do |s| %>
            <li>
              <%= link_to "#{s.staff_member.login} - #{s.staff_member.full_name}", year_staff_member_path(@year, s.staff_member) %>
            </li>
          <% end %>
        </ul>
      <% end %>
    <% end %>
  </div>
</div>