config/routes.rb
DoctorPrototype::Application.routes.draw do

  root :to => 'years#index'

  put 'years/:year_id/clashes',
    :to => 'clashes#update',
    :as => :update_clashes

  delete 'years/:year_id/unclashables',
    :to => 'unclashables#remove',
    :as => :remove_unclashable

  put 'years/:id/generate_timetable',
    :to => 'years#generate_timetable',
    :as => :year_generate_timetable

  resources :years, :except => [:destroy] do
    resources :requirements, :only => [] do
      collection do
        post 'import'
      end
    end
    resources :precisely_clauses, :only => [:index] do
      collection do
        put 'update'
      end
    end
    resources :preference_clauses, :only => [:index] do
      collection do
        put 'update'
      end
    end
    resources :terms, :only => [] do
      member do
        get 'timetable_slots'
      end
    end
    resources :lecturers, :only => [] do
      collection do
        post 'import'
      end
    end
    resources :rooms, :except => [:show] do
      member do
        get 'timetable_slots'
      end
    end
    resources :degree_classes, :only => [:index, :show] do
      collection do
        post 'import'
      end
    end
    resources :staff_members, :only => [:index, :show] do
      collection do
        post 'import'
      end
    end
    resources :lecture_courses, :only => [:index, :show], :constraints => { :id => /[^\/]+(?=\.html\z|\.json\z)|[^\/]+/ } do
      member do
        post 'show_clashes'
        delete 'hide_clashes'
        put 'update_course_weeks'
      end
      collection do
        post 'import'
      end
    end
    resources :clashes, :only => [:index, :new]
    resources :unclashables, :only => [:create]
    resources :timetable_slots, :only => [:index]
  end
end

app/models/room.rb
class Room < ActiveRecord::Base

  attr_accessible :no, :capacity, :year, :room_type, :size

  # = Validations =
  validates_presence_of :no, :capacity, :year, :room_type, :size

  # = Relationships =
  has_many :timetable_slots
  belongs_to :year

  # = Scopes =
  scope :by_no, order('no')

  def to_param
    no
  end

  def to_ASP
    "#{room_type}_room(\"#{no}\")."
  end

  def size_to_ASP
    "room_size(\"#{no}\", #{size}\)."
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @year = Year.find_by_no(params[:year_id])
    @rooms = @year.rooms.by_no
  end

  def new
    @year = Year.find_by_no(params[:year_id])
    @room = @year.rooms.build
  end

  def create
    @year = Year.find_by_no(params[:year_id])
    @room = @year.rooms.build(params[:room])
    if @room.save
      Resque.enqueue(RoomWriterWorker, @year.no)
      redirect_to year_rooms_path(@year), :notice => "Room was created successfully."
    else
      flash[:warning] = "Room could not be created."
      render :new
    end
  end

  def edit
    @year = Year.find_by_no(params[:year_id])
    @room = @year.rooms.find_by_no(params[:id])
  end

  def update
    @year = Year.find_by_no(params[:year_id])
    @room = @year.rooms.find_by_no(params[:id])
    if @room.update_attributes(params[:room])
      Resque.enqueue(RoomWriterWorker, @year.no)
      redirect_to year_rooms_path(@year), :notice => "Room was successfully updated."
    else
      flash[:warning] = "Room could not be updated."
      render :edit
    end
  end

  def destroy
    @year = Year.find_by_no(params[:year_id])
    @room = @year.rooms.find_by_no(params[:id])
    @room.destroy
    redirect_to year_rooms_path(@year), :notice => "Room was deleted successfully."
  end

  def timetable_slots
    @year = Year.find_by_no(params[:year_id])
    @room = @year.rooms.find_by_no(params[:id])
    @time_slots = TimeSlot.scoped
    @slots = group_slots(@year.timetable_slots.where(:room_id => @room.id))
  end

  private
  def group_slots(slots)
    by_term = slots.group_by { |s| s.week.term }
    by_term_and_time_slot = {}
    by_term.each_pair do |term, term_slots|
      by_term_and_time_slot[term] = term_slots.group_by { |t| t.time_slot }
      by_term_and_time_slot[term].each_pair do |slot, slot_allocs|
        by_term_and_time_slot[term][slot] = slot_allocs.group_by { |s| s.lecture_course }
        by_term_and_time_slot[term][slot].each_pair do |course, course_allocs|
          by_term_and_time_slot[term][slot][course] = course_allocs.group_by { |c| c.slot_type }
        end
      end
    end
    by_term_and_time_slot
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def room_type_options(room)
    options_for_select([["Lecture", "lecture"], ["Lab", "lab"]], room.room_type)
  end

  def room_size_options(room)
    options = []
    ['small', 'medium', 'large'].each do |size|
      options << [size.capitalize, size]
    end

    options_for_select(options, room.size)
  end
end

app/views/rooms/_form.html.erb
<%= form_for [@year, @room], :html => { :class => 'form-horizontal' } do |f| %>
  <%= render 'shared/error_messages', :target => @room %>
    <div class="control-group">
      <%= f.label :no, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :no, :disabled => params[:action] == 'edit' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :capacity, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :capacity %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :room_type, :class => "control-label" %>
      <div class="controls">
        <%= f.select :room_type, room_type_options(@room) %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :size, :class => "control-label" %>
      <div class="controls">
        <%= f.select :size, room_size_options(@room) %>
      </div>
    </div>

  <div class="control-group">
    <div class="controls">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/rooms/_timetable_term.html.erb
<h4>
  Term <%= term.no %>
</h4>

<table class="table table-bordered">
  <tr>
    <th></th>
    <% Day.all.each do |d| %>
      <th>
        <%= d.name %>
      </th>
    <% end %>
  </tr>

  <% 1.upto(9) do |time| %>
    <tr>
      <td>
        <%= time %>
      </td>
      <% Day.all.each do |d| %>
        <td>
          <% if allocs[@time_slots.where(:day_id => d.id, :start_hour => time).first].present? %>
            <% allocs[@time_slots.where(:day_id => d.id, :start_hour => time).first].each_pair do |course, course_allocs| %>
              <%= course.code %>
              <ul>
                <% course_allocs.each_pair do |type, type_allocs| %>
                  <li>
                    <%= type.capitalize %> (<%= get_week_ranges(type_allocs.map { |t| t.week.no }.sort ) %>)
                  </li>
                <%  end %>
              </ul>
            <% end %>
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/rooms/edit.html.erb
<div class="row" id='inner-header'>
  <div class='span6 sub-header'>
    <h2>
      Edit room
    </h2>
  </div>
  <div class='span6 sub-header'>
    <div class='header-actions'>
      <%= back_button("rooms", year_rooms_path(@year)) %>
    </div>
  </div>
</div>

<hr>

<%= render 'form' %>

app/views/rooms/index.html.erb
<div class="row" id='inner-header'>
  <div class='span6 sub-header'>
    <h2>
      Rooms
    </h2>
  </div>
  <div class='span6 sub-header'>
    <div class='header-actions'>
      <%= link_to "Create Room", new_year_room_path(@year), :class => "btn btn-primary" %>
      <%= back_button(@year.no, year_path(@year)) %>
    </div>
  </div>
</div>

<hr>

<% if @rooms.empty? %>
  <div class="alert alert-block">
    No rooms to show.
  </div>
<% else %>
  <table class="table table-striped">
    <tr>
      <th>
        Room
      </th>
      <th>
        Size
      </th>
      <th>
        Room Type
      </th>
      <th> </th>
    </tr>

    <% @rooms.each do |r| %>
      <tr>
        <td>
          <%= r.no %>
        </td>
        <td>
          <%= r.size.capitalize %>
        </td>
        <td>
          <%= r.room_type.capitalize %>
        </td>
        <td>
          <%= link_to "Edit", edit_year_room_path(@year, r), :class => "btn btn-primary" %>
          <%= link_to "Delete", year_room_path(@year, r), :method => :delete, :data => { :confirm => "Are you sure you wish to delete this room?" }, :class => "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/rooms/new.html.erb
<div class="row" id='inner-header'>
  <div class='span6 sub-header'>
    <h2>
      New room
    </h2>
  </div>
  <div class='span6 sub-header'>
    <div class='header-actions'>
      <%= back_button("rooms", year_rooms_path(@year)) %>
    </div>
  </div>
</div>

<hr>

<%= render 'form' %>

app/views/rooms/timetable_slots.html.erb
<div class="row" id='inner-header'>
  <div class='span6 sub-header'>
    <h2>
      Timetable for Room <%= @room.no %>
    </h2>
  </div>
  <div class='span6 sub-header'>
    <div class='header-actions'>
      <%= back_button("timetable", year_timetable_slots_path(@year)) %>
    </div>
  </div>
</div>

<hr>

<% @slots.each_pair do |term, allocs| %>
  <%= render :partial => 'timetable_term', :locals => { :term => term, :allocs => allocs } %>
<% end %>