config/routes.rb
DoctorPrototype::Application.routes.draw do

  root :to => 'years#index'

  put 'years/:year_id/clashes',
    :to => 'clashes#update',
    :as => :update_clashes

  delete 'years/:year_id/unclashables',
    :to => 'unclashables#remove',
    :as => :remove_unclashable

  put 'years/:id/generate_timetable',
    :to => 'years#generate_timetable',
    :as => :year_generate_timetable

  resources :years, :except => [:destroy] do
    resources :requirements, :only => [] do
      collection do
        post 'import'
      end
    end
    resources :precisely_clauses, :only => [:index] do
      collection do
        put 'update'
      end
    end
    resources :preference_clauses, :only => [:index] do
      collection do
        put 'update'
      end
    end
    resources :terms, :only => [] do
      member do
        get 'timetable_slots'
      end
    end
    resources :lecturers, :only => [] do
      collection do
        post 'import'
      end
    end
    resources :rooms, :except => [:show] do
      member do
        get 'timetable_slots'
      end
    end
    resources :degree_classes, :only => [:index, :show] do
      collection do
        post 'import'
      end
    end
    resources :staff_members, :only => [:index, :show] do
      collection do
        post 'import'
      end
    end
    resources :lecture_courses, :only => [:index, :show], :constraints => { :id => /[^\/]+(?=\.html\z|\.json\z)|[^\/]+/ } do
      member do
        post 'show_clashes'
        delete 'hide_clashes'
        put 'update_course_weeks'
      end
      collection do
        post 'import'
      end
    end
    resources :clashes, :only => [:index, :new]
    resources :unclashables, :only => [:create]
    resources :timetable_slots, :only => [:index]
  end
end

app/controllers/degree_classes_controller.rb
class DegreeClassesController < ApplicationController
  def index
    @year = Year.find_by_no(params[:year_id])
    @degrees = @year.degree_classes.by_degreeyr
  end

  def show
    @year = Year.find_by_no(params[:year_id])
    @degree = @year.degree_classes.find_by_degreeyr(params[:id])
    @requirements = @degree.requirements
  end

  def import
    @year = Year.find_by_no(params[:year_id])
    tempfile = params[:file]
    FileUtils::cp(tempfile.tempfile.path, Rails.root.join("tmp", tempfile.original_filename))
    Resque.enqueue(DegreeClassImporterWorker, @year.no, tempfile.original_filename)
    redirect_to year_path(@year), :notice => "Importing degree classes."
  end
end

app/views/degree_classes/_import_form.html.erb
<%= form_tag(import_year_degree_classes_path(@year), :multipart => true, :class => "form-horizontal") do %>
  <h3>
    Import Degree Classes
  </h3>

  <div class='control-group'>
    <div class='controls'>
      <%= file_field_tag "file" %>
    </div>
  </div>

  <div class='form-actions'>
    <%= submit_tag "Upload", :class => 'btn btn-primary' %>
  </div>

<% end %>

app/views/degree_classes/index.html.erb
<div class="row" id='inner-header'>
  <div class='span6 sub-header'>
    <h2>
      Degree Classes
    </h2>
  </div>
  <div class='span6 sub-header'>
    <div class='header-actions'>
      <%= back_button(@year.no, year_path(@year)) %>
    </div>
  </div>
</div>

<hr>

<% if @degrees.empty? %>
  <div class="alert alert-block">
    No degrees to show.
  </div>
<% else %>
  <ul class='nav nav-pills nav-stacked'>
    <% @degrees.each do |d| %>
      <li>
        <%= link_to "#{d.degreeyr} - #{d.title}", year_degree_class_path(@year, d) %>
      </li>
    <% end %>
  </ul>
<% end %>

<hr>

<%= render :partial => 'import_form' %>

<hr>

<%= render :partial => 'requirements/import_form' %>

app/views/degree_classes/show.html.erb
<div class="row" id='inner-header'>
  <div class='span6 sub-header'>
    <h2>
      <%= @degree.degreeyr %> - <%= @degree.title %>
    </h2>
  </div>
  <div class='span6 sub-header'>
    <div class='header-actions'>
      <%= back_button(@year.no, year_path(@year)) %>
    </div>
  </div>
</div>

<hr>

<% if @requirements.empty? %>
  <h3>
    There are no requirements for this degree.
  </h3>
<% else %>
  <h3>
    Options:
  </h3>
  <% @requirements.group_by(&:required).each do |required, classes| %>
    <h4>
      <%= required %>
    </h4>
    <ul class='nav nav-pills nav-stacked'>
      <% classes.each do |c| %>
        <li>
          <%= link_to "#{c.lecture_course.code} - #{c.lecture_course.title}", year_lecture_course_path(@year, c.lecture_course) %>
        </li>
      <% end %>
    </ul>
  <% end %>
<% end %>